CREATE TABLE "possible_game_attempts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"result" text,
	CONSTRAINT "possible_game_attempts_result_check" CHECK ("possible_game_attempts"."result" is null or "possible_game_attempts"."result" in ('died', 'finished'))
);
--> statement-breakpoint
CREATE TABLE "possible_game_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "possible_game_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"display_name" text NOT NULL,
	"result" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "possible_game_events_result_check" CHECK ("possible_game_events"."result" in ('died', 'finished'))
);
--> statement-breakpoint
CREATE TABLE "possible_game_presence" (
	"connection_id" uuid PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"display_name" text NOT NULL,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "possible_game_profiles" (
	"user_id" text PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "possible_game_stats" (
	"user_id" text PRIMARY KEY NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"finishes" integer DEFAULT 0 NOT NULL,
	"current_streak" integer DEFAULT 0 NOT NULL,
	"longest_streak" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "possible_game_stats_attempts_check" CHECK ("possible_game_stats"."attempts" >= 0),
	CONSTRAINT "possible_game_stats_finishes_check" CHECK ("possible_game_stats"."finishes" >= 0),
	CONSTRAINT "possible_game_stats_finishes_attempts_check" CHECK ("possible_game_stats"."finishes" <= "possible_game_stats"."attempts"),
	CONSTRAINT "possible_game_stats_current_streak_check" CHECK ("possible_game_stats"."current_streak" >= 0),
	CONSTRAINT "possible_game_stats_longest_streak_check" CHECK ("possible_game_stats"."longest_streak" >= "possible_game_stats"."current_streak")
);
--> statement-breakpoint
ALTER TABLE "possible_game_attempts" ADD CONSTRAINT "possible_game_attempts_user_id_possible_game_profiles_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."possible_game_profiles"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "possible_game_stats" ADD CONSTRAINT "possible_game_stats_user_id_possible_game_profiles_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."possible_game_profiles"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "possible_game_attempts_user_started_idx" ON "possible_game_attempts" USING btree ("user_id","started_at");--> statement-breakpoint
CREATE INDEX "possible_game_events_created_idx" ON "possible_game_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "possible_game_presence_last_seen_idx" ON "possible_game_presence" USING btree ("last_seen_at");--> statement-breakpoint
CREATE INDEX "possible_game_presence_user_idx" ON "possible_game_presence" USING btree ("user_id");